title: RF PLL System Model
author: PhillipRambo

execute:
  execute_notebooks: "off"

html:
  use_issues_button: true
  use_repository_button: true

repository:
  url: https://github.com/PhillipRambo/rf-system-model

latex:
  latex_documents:
    targetname: book.tex
